- name: Install Jujhar's apt Software
  apt:
    pkg:
      - audacity
      - bambam # baby keyboard mashing software
      - bmon
      - build-essential
      - chrome-gnome-shell
      - chromium-browser
      - clamav
      - clamav-daemon
      - clamtk
      - conky
      - curl
      - filezilla
      - firefox
      - forensics-all
      - gcc
      - git
      - gimp
      - gnome
      - gnome-tweaks
      - gnome-shell-extension-no-annoyance
      - gnome-shell-extension-caffeine
      - golang-go
      - golint
      - grep
      - htop
      - inotify-tools
      - iotop
      - jq
      - lastpass-cli
      - libcanberra-gtk-module
      - liferea
      - make
      - mycli
      - nautilus-admin
      - nautilus-extension-gnome-terminal
      - nautilus-font-manager
      - nautilus-image-converter
      - nautilus-wipe
      - ncdu
      - nethogs
      - net-tools
      - nmap
      - notepadqq #gedit replacement
      - obs-studio # live stream tool
      - openshot # video editor
      - openvpn
      - pandoc
      - pass
      - picard # Next-Generation MusicBrainz audio files tagger
      - powertop
      - pwgen
      - python3-pip
      - rsync
      - shellcheck
      - socat
      - sox #- Swiss army knife of sound processing
      - tar
      - terminator
      - tig
      - tlp
      - tlp-rdw
      - tmux
      - tree
      - ubuntu-restricted-extras # MP3, Microsoft fonts, Flash plugin, LAME and DVD playback
      - unzip
      - wget
      - whois
      - vim
      - vim-pathogen
      - vim-gtk3
      - vim-syntastic
      - vim-syntax-docker
      - vlc
      - xclip # to manipulate the clipboard
      - xstow
      - youtube-dl
      - zip
      - zsh
    state: latest
    update_cache: true

- name: Install python packages
  pip:
    name:
      #- aws-cli
      - termtime
